// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/17/2024, 12:59:53 PM
const configMerger = require("D:/Homefood/01/homefood/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["D:/Homefood/01/homefood/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Homefood/01/homefood/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Homefood/01/homefood/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Homefood/01/homefood/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Homefood/01/homefood/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Homefood/01/homefood/plugins/**/*.{js,ts,mjs}","D:/Homefood/01/homefood/composables/**/*.{js,ts,mjs}","D:/Homefood/01/homefood/utils/**/*.{js,ts,mjs}","D:/Homefood/01/homefood/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Homefood/01/homefood/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Homefood/01/homefood/app.config.{js,ts,mjs}"] } }));

module.exports = config
