// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/15/2024, 9:05:28 AM
const configMerger = require("C:/Users/xctxc/OneDrive/เดสก์ท็อป/term_2_project/homefood/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Users/xctxc/OneDrive/เดสก์ท็อป/term_2_project/homefood/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/xctxc/OneDrive/เดสก์ท็อป/term_2_project/homefood/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/xctxc/OneDrive/เดสก์ท็อป/term_2_project/homefood/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/xctxc/OneDrive/เดสก์ท็อป/term_2_project/homefood/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/xctxc/OneDrive/เดสก์ท็อป/term_2_project/homefood/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/xctxc/OneDrive/เดสก์ท็อป/term_2_project/homefood/plugins/**/*.{js,ts,mjs}","C:/Users/xctxc/OneDrive/เดสก์ท็อป/term_2_project/homefood/composables/**/*.{js,ts,mjs}","C:/Users/xctxc/OneDrive/เดสก์ท็อป/term_2_project/homefood/utils/**/*.{js,ts,mjs}","C:/Users/xctxc/OneDrive/เดสก์ท็อป/term_2_project/homefood/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/xctxc/OneDrive/เดสก์ท็อป/term_2_project/homefood/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/xctxc/OneDrive/เดสก์ท็อป/term_2_project/homefood/app.config.{js,ts,mjs}"] } }));

module.exports = config
