// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 13/11/2024, 15:09:17
const configMerger = require("/Users/sirawitkumlungsri/Documents/GitHub/homefood/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/sirawitkumlungsri/Documents/GitHub/homefood/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sirawitkumlungsri/Documents/GitHub/homefood/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sirawitkumlungsri/Documents/GitHub/homefood/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sirawitkumlungsri/Documents/GitHub/homefood/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sirawitkumlungsri/Documents/GitHub/homefood/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sirawitkumlungsri/Documents/GitHub/homefood/plugins/**/*.{js,ts,mjs}","/Users/sirawitkumlungsri/Documents/GitHub/homefood/composables/**/*.{js,ts,mjs}","/Users/sirawitkumlungsri/Documents/GitHub/homefood/utils/**/*.{js,ts,mjs}","/Users/sirawitkumlungsri/Documents/GitHub/homefood/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/sirawitkumlungsri/Documents/GitHub/homefood/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/sirawitkumlungsri/Documents/GitHub/homefood/app.config.{js,ts,mjs}"] } }));

module.exports = config
